apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-signal 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
  storageClassName: longhorn