apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: pvc-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn