apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: pvc-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn