apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: pvc-kuma 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn